### ISSUE TITLE
Module d'inscription

### ISSUE THREAD

**Issue by erwanosouf** [blank-project/website#28]

**Comment by FaXaq** [comment]
Comment on le fait ? Google form ?

**Comment by erwanosouf** [comment]
Je pense ouais, voir l'ancien site

Le 30 août 2016 9:51 AM, "Marin Procureur" notifications@github.com a
écrit :

**Comment by erwanosouf** [comment]
Texte intro : Les inscriptions pour la promotion 2016/17 sont ouvertes. La rentrée aura lieu le 3 novembre 2016. Les candidats seront convoqués pour une présentation collective ainsi que pour un entretien individuel. Aucun diplôme n’est requis pour postuler, on attendra seulement des candidats une maîtrise du français ainsi que des bases de bureautique informatique (envoyer un mail, naviguer sur internet), de la curiosité et beaucoup de motivation ! La période de formation étant longue et le rythme intensif, les candidats devront s’assurer d’être disponible et présents sur toute la durée de la formation.

 S’inspirer du formulaire de l’année dernière, essayer de récolter le maximum d’info, rendre les réponses obligatoires
