### ISSUE TITLE
Review website content

### ISSUE THREAD

**Issue by erwanosouf** [blank-project/website#3]

**Comment by Pauleing** [comment]
@erwanosouf tu peux m'envoyer ta base par mail ? Je retrouve pas le mail qui contenait ça - s'il a un jour existé

**Comment by erwanosouf** [comment]
J'ai comité la structure, tout est sur le repo

Pour le contenu j'ai rien touché.

**Comment by Pauleing** [comment]
est-ce que Antonin nous avait envoyé un texte ? Si oui j'ai perdu le mail, peux-tu me le renvoyer ?

**Comment by erwanosouf** [comment]
Done. Ta bonne adresse c'est celle avec les points ou celle sans ?

**Comment by Pauleing** [comment]
Avec les points I guess

**Comment by Pauleing** [comment]
Je fais une proposition ce midi, pas eu le temps hier.

**Comment by erwanosouf** [comment]
J'ai pushé des bricoles entre temps je regarde ce soir

**Comment by erwanosouf** [comment]
Je vais m'y mettre soon tu peux pusher avant ?
