### ISSUE TITLE
Logo Fondation de France

### ISSUE THREAD

**Issue by TotorBelleville** [blank-project/website#44]
Ajouter logo fondation sur la page partenaires

Ici : http://fondationdefrance.org/article/logo-projet-soutenu

<a target="_blank" href="http://www.fondationdefrance.org"><img src="http://www.fondationdefrance.org/sites/default/files/thumbnails/image/logo-projet-soutenu-couleur.jpg" border=no alt="Projet soutenu par la Fondation de France"/></a>

**Comment by TotorBelleville** [comment]
Voici le logo

![logo-projet-soutenu-couleur](https://cloud.githubusercontent.com/assets/23259599/20529814/cfc2c650-b0d1-11e6-91e0-72c13e870e84.jpg)

**Comment by FaXaq** [comment]
closed by af5fd8f1be04aa3013bed53820b4e3b59b8fd4bf
