### ISSUE TITLE
Formulaire projet insertion

### ISSUE THREAD

**Issue by TotorBelleville** [blank-project/website#47]
Créer un onglet "Services" sur la front page 

Sur la page mettre le texte suivant : 

"Les deux derniers mois de la formation sont consacrés à la réalisation par les apprenant.e.s de cinq sites web destinés à soutenir les initiatives locales et à accompagner la transition numérique des acteurs associatifs du quartier. Cette mise en application sur projet réel permet aux apprenant.e.s d’avoir une première expérience professionnelle tout en contribuant activement à l’intérêt général local. 
_blank recherche des structures ayant une idée précise de leur projet. Vous pouvez nous soumettre un premier cahier des charges en remplissant ce formulaire avant le 25 janvier 2017. 
La finalisation du cahier des charges et la signature d’une convention de partenariat auront lieu au mois de février 2017. Les sites web seront réalisés de mars à avril 2017 pour une mise en production début mai. Selon la difficulté du projet, une contribution financière pourra vous être demandée."

Puis créer un formulaire avec les questions suivantes: 

1) Identification du commanditaire : 
- Nom de la structure :
- Statut de la structure (association, TPE, collectif…) : 
- Nombre d’employés/ de bénévoles :
- Adresse de la structure :
- Nom, prénom du contact :
- Fonction du contact dans la structure : 
- Mail du contact :
- téléphone du contact :
- Avez vous des liens pour consulter l’actualité de votre structure (réseaux sociaux, site, blog) ?:

2) Description du projet :
- Nom du projet (s’il existe) :
- Objectif du projet :
- Rapide descriptif du projet (10 lignes max) :
- Souhaitez-vous que le prestataire prenne en charge l’hébergement ?
-  S’agit il d’une refonte d’un site web existant ? Si oui, quelle est l’adresse du site ? 
- Votre projet est-il un site permanent ou dédié à un événement (dans ce cas, indiquez lequel et les dates de ce dernier) ?
- Quelle est la (ou les) cible(s) de votre projet (particuliers, entreprises, adultes, ados, etc) ?
- Quelles sont les caractéristiques et les centres d’intérêt de votre cible ?
- Combien de décideurs devront valider chaque étape du projet ? Quels sont ils (nom et fonction) ?
- De combien de temps (nombre d'heure) par semaine disposerez vous pour vous consacrer au suivi de ce projet ?
- Pouvez vous accueillir les stagiaires en formation au sein de votre structure au cours de la réalisation du projet ? Si oui, combien de jours par semaine ?
- Quelles sont les contraintes à prendre en compte dans la réalisation du projet ?
- Avez vous des contraintes de dates pour la livraison du projet ? Lesquelles ?

3) Fonctionnalités du projet : 
- Quel type de site souhaitez vous  (blog, e-commerce, site vitrine, média en ligne, autre) ?
- Listez les contenus à intégrer sur le site dont vous disposez déjà (textes, photos, vidéos…) :
- Quelle sont les grandes sections de votre site ? Comment sont organisées les différentes rubriques ? Quelles sont les pages principales ? 
- Disposez vous d’une identité graphique (logo, design, couleurs) applicable au projet ? Quelles sont les ressources disponibles ?
- Version adaptée au mobile/tablette (responsive) ? Oui/Non
- Réseaux sociaux ? (oui/non)
- Disposez vous d’un nom de domaine associé au projet ? Si oui lequel ?
-  Doit-il y avoir un espace client sécurisé par mot de passe ? Oui/non
- Précisez les autres fonctionnalités du site :

Pour toute information ou envoi de documents complémentaires : blank@bellevillecitoyenne.fr

**Comment by erwanosouf** [comment]
Changer Mise en production en Livraison (on va pas forcément mettre en prod)

**Comment by erwanosouf** [comment]
Retirer le passage sur la contribution financière ou le préciser

**Comment by TotorBelleville** [comment]
<div class="typeform-widget" data-url="https://blank6.typeform.com/to/x6DuSY" data-text="_blank développe votre site web" style="width:100%;height:500px;"></div>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'widget.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>
<div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;">Powered by<a href="https://www.typeform.com/examples/?utm_campaign=x6DuSY&amp;utm_source=typeform.com-6127170-Basic&amp;utm_medium=typeform&amp;utm_content=typeform-embedded-poweredbytypeform&amp;utm_term=FR" style="color: #999" target="_blank">Typeform</a></div>

**Comment by TotorBelleville** [comment]
<div class="typeform-widget" data-url="https://blank6.typeform.com/to/x6DuSY" data-text="_blank développe votre site web" style="width:100%;height:500px;"></div>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'widget.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>
<div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;">Powered by<a href="https://www.typeform.com/examples/?utm_campaign=x6DuSY&amp;utm_source=typeform.com-6127170-Basic&amp;utm_medium=typeform&amp;utm_content=typeform-embedded-poweredbytypeform&amp;utm_term=FR" style="color: #999" target="_blank">Typeform</a></div>

**Comment by TotorBelleville** [comment]
<div class="typeform-widget" data-url="https://blank6.typeform.com/to/x6DuSY" data-text="_blank développe votre site web" style="width:100%;height:500px;"></div>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'widget.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>
<div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;">Powered by<a href="https://www.typeform.com/examples/?utm_campaign=x6DuSY&amp;utm_source=typeform.com-6127170-Basic&amp;utm_medium=typeform&amp;utm_content=typeform-embedded-poweredbytypeform&amp;utm_term=FR" style="color: #999" target="_blank">Typeform</a></div>``
