### ISSUE TITLE
Add team presentation

### ISSUE THREAD

**Issue by erwanosouf** [blank-project/website#9]
Use .img-circle for increased swag

**Comment by yohanngab** [comment]
J'ai commencé je push demain matin

Yohann Gablowski
06 82 99 93 52

**Comment by yohanngab** [comment]
@erwanosouf @Pauleing Vous avez le contenu des descriptions de la team ? je le trouve ap

**Comment by Pauleing** [comment]
ça doit traîner dans un doc quelque part, demande à Totor

**Comment by erwanosouf** [comment]
https://docs.google.com/document/d/1-11upq4PdTsVYSTBfiOvPCVT9NmO_E9zQdMhTZTj_JI/edit?usp=docslist_api

**Comment by Pauleing** [comment]
Elles sont super pixélisées les tofs sur un téléphone c'est horrible .

**Comment by yohanngab** [comment]
Chelou, je verrai ça tarplu

Yohann Gablowski
06 82 99 93 52
Le 16 oct. 2015 19:39, "Paulin de Naurois" notifications@github.com a
écrit :
